# Generated by Django 5.0.7 on 2024-07-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_customperiodictask"),
        ("task", "0002_migrate_scheduler"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomPeriodicTask",
        ),
    ]
